from __future__ import annotations
from enum import Enum


class WorkflowState(str, Enum):
    CREATED = "CREATED"
    PROJECT_READY = "PROJECT_READY"
    MODULE_READY = "MODULE_READY"
    PAGE_CREATED = "PAGE_CREATED"
    DISCOVERY_RUNNING = "DISCOVERY_RUNNING"
    DISCOVERY_DONE = "DISCOVERY_DONE"
    LOCATORS_RANKED = "LOCATORS_RANKED"
    PAGE_SAVED = "PAGE_SAVED"
    SCENARIOS_GENERATING = "SCENARIOS_GENERATING"
    SCENARIOS_READY = "SCENARIOS_READY"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    TESTCASES_GENERATING = "TESTCASES_GENERATING"
    TESTCASES_READY = "TESTCASES_READY"
    REVIEW_READY = "REVIEW_READY"
    COMPLETED = "COMPLETED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


STATE_PROGRESS: dict[WorkflowState, int] = {
    WorkflowState.CREATED: 5,
    WorkflowState.PROJECT_READY: 10,
    WorkflowState.MODULE_READY: 15,
    WorkflowState.PAGE_CREATED: 20,
    WorkflowState.DISCOVERY_RUNNING: 35,
    WorkflowState.DISCOVERY_DONE: 50,
    WorkflowState.LOCATORS_RANKED: 65,
    WorkflowState.PAGE_SAVED: 75,
    WorkflowState.SCENARIOS_GENERATING: 82,
    WorkflowState.SCENARIOS_READY: 88,
    WorkflowState.AWAITING_CONFIRMATION: 88,
    WorkflowState.TESTCASES_GENERATING: 92,
    WorkflowState.TESTCASES_READY: 94,
    WorkflowState.REVIEW_READY: 96,
    WorkflowState.COMPLETED: 100,
    WorkflowState.STOPPED: 0,
    WorkflowState.FAILED: 0,
}
